build:
  image: python:2
  commands:
    - echo "Building"

publish:
  docker:
    repo: $$DOCKER_ORG/$$DOCKER_REPO
    tag: "$${BRANCH##feature/}"
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL

  docker:
    repo: $$DOCKER_ORG/$$DOCKER_REPO
    tag: "latest"
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    when:
      branch: "master"

  docker:
    context: sample_client_app/
    repo: $$DOCKER_ORG/$$DOCKER_REPO_client
    tag: "$${BRANCH##feature/}"
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL

  docker:
    context: sample_client_app/
    repo: $$DOCKER_ORG/$$DOCKER_REPO_client
    tag: "latest"
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    when:
      branch: "master"


deploy:
  webhook:
    image: plugins/drone-webhook
    skip_verify: true
    method: POST
    auth:
      username: $$MANTL_USERNAME
      password: $$MANTL_PASSWORD
    urls:
      - https://$$MANTL_CONTROL/marathon/v2/apps/$$MANTL_APP_ID-dev/restart?force=true
    when:
      branch: "dev"

  webhook:
    image: plugins/drone-webhook
    skip_verify: true
    method: POST
    auth:
      username: $$MANTL_USERNAME
      password: $$MANTL_PASSWORD
    urls:
      - https://$$MANTL_CONTROL/marathon/v2/apps/$$MANTL_APP_ID/restart?force=true
    when:
      branch: "master"

notify:
  spark:
    image: hpreston/drone-spark
    auth_token: $$SPARK_TOKEN
    roomId: $$SPARK_ROOM
